#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbPinkCosmetics")]
	public partial class PinkCosmeticsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_BangGia(tb_BangGia instance);
    partial void Updatetb_BangGia(tb_BangGia instance);
    partial void Deletetb_BangGia(tb_BangGia instance);
    partial void Inserttb_ThuongHieu(tb_ThuongHieu instance);
    partial void Updatetb_ThuongHieu(tb_ThuongHieu instance);
    partial void Deletetb_ThuongHieu(tb_ThuongHieu instance);
    partial void Inserttb_ChiTietHDBan(tb_ChiTietHDBan instance);
    partial void Updatetb_ChiTietHDBan(tb_ChiTietHDBan instance);
    partial void Deletetb_ChiTietHDBan(tb_ChiTietHDBan instance);
    partial void Inserttb_ChiTietHDNhap(tb_ChiTietHDNhap instance);
    partial void Updatetb_ChiTietHDNhap(tb_ChiTietHDNhap instance);
    partial void Deletetb_ChiTietHDNhap(tb_ChiTietHDNhap instance);
    partial void Inserttb_GiaBan(tb_GiaBan instance);
    partial void Updatetb_GiaBan(tb_GiaBan instance);
    partial void Deletetb_GiaBan(tb_GiaBan instance);
    partial void Inserttb_HoaDonBan(tb_HoaDonBan instance);
    partial void Updatetb_HoaDonBan(tb_HoaDonBan instance);
    partial void Deletetb_HoaDonBan(tb_HoaDonBan instance);
    partial void Inserttb_HoaDonNhap(tb_HoaDonNhap instance);
    partial void Updatetb_HoaDonNhap(tb_HoaDonNhap instance);
    partial void Deletetb_HoaDonNhap(tb_HoaDonNhap instance);
    partial void Inserttb_KhachHang(tb_KhachHang instance);
    partial void Updatetb_KhachHang(tb_KhachHang instance);
    partial void Deletetb_KhachHang(tb_KhachHang instance);
    partial void Inserttb_NhanVien(tb_NhanVien instance);
    partial void Updatetb_NhanVien(tb_NhanVien instance);
    partial void Deletetb_NhanVien(tb_NhanVien instance);
    partial void Inserttb_NhomSanPham(tb_NhomSanPham instance);
    partial void Updatetb_NhomSanPham(tb_NhomSanPham instance);
    partial void Deletetb_NhomSanPham(tb_NhomSanPham instance);
    partial void Inserttb_SanPham(tb_SanPham instance);
    partial void Updatetb_SanPham(tb_SanPham instance);
    partial void Deletetb_SanPham(tb_SanPham instance);
    partial void Inserttb_TaiKhoan(tb_TaiKhoan instance);
    partial void Updatetb_TaiKhoan(tb_TaiKhoan instance);
    partial void Deletetb_TaiKhoan(tb_TaiKhoan instance);
    #endregion
		
		public PinkCosmeticsDataContext() : 
				base(global::DTO.Properties.Settings.Default.dbPinkCosmeticsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PinkCosmeticsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PinkCosmeticsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PinkCosmeticsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PinkCosmeticsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_BangGia> tb_BangGias
		{
			get
			{
				return this.GetTable<tb_BangGia>();
			}
		}
		
		public System.Data.Linq.Table<tb_ThuongHieu> tb_ThuongHieus
		{
			get
			{
				return this.GetTable<tb_ThuongHieu>();
			}
		}
		
		public System.Data.Linq.Table<tb_ChiTietHDBan> tb_ChiTietHDBans
		{
			get
			{
				return this.GetTable<tb_ChiTietHDBan>();
			}
		}
		
		public System.Data.Linq.Table<tb_ChiTietHDNhap> tb_ChiTietHDNhaps
		{
			get
			{
				return this.GetTable<tb_ChiTietHDNhap>();
			}
		}
		
		public System.Data.Linq.Table<tb_GiaBan> tb_GiaBans
		{
			get
			{
				return this.GetTable<tb_GiaBan>();
			}
		}
		
		public System.Data.Linq.Table<tb_HoaDonBan> tb_HoaDonBans
		{
			get
			{
				return this.GetTable<tb_HoaDonBan>();
			}
		}
		
		public System.Data.Linq.Table<tb_HoaDonNhap> tb_HoaDonNhaps
		{
			get
			{
				return this.GetTable<tb_HoaDonNhap>();
			}
		}
		
		public System.Data.Linq.Table<tb_Identity> tb_Identities
		{
			get
			{
				return this.GetTable<tb_Identity>();
			}
		}
		
		public System.Data.Linq.Table<tb_KhachHang> tb_KhachHangs
		{
			get
			{
				return this.GetTable<tb_KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<tb_NhanVien> tb_NhanViens
		{
			get
			{
				return this.GetTable<tb_NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tb_NhomSanPham> tb_NhomSanPhams
		{
			get
			{
				return this.GetTable<tb_NhomSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tb_SanPham> tb_SanPhams
		{
			get
			{
				return this.GetTable<tb_SanPham>();
			}
		}
		
		public System.Data.Linq.Table<tb_TaiKhoan> tb_TaiKhoans
		{
			get
			{
				return this.GetTable<tb_TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_BangGia")]
	public partial class tb_BangGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBangGia;
		
		private string _TenBangGia;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_ChiTietHDBan> _tb_ChiTietHDBans;
		
		private EntitySet<tb_GiaBan> _tb_GiaBans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBangGiaChanging(int value);
    partial void OnMaBangGiaChanged();
    partial void OnTenBangGiaChanging(string value);
    partial void OnTenBangGiaChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_BangGia()
		{
			this._tb_ChiTietHDBans = new EntitySet<tb_ChiTietHDBan>(new Action<tb_ChiTietHDBan>(this.attach_tb_ChiTietHDBans), new Action<tb_ChiTietHDBan>(this.detach_tb_ChiTietHDBans));
			this._tb_GiaBans = new EntitySet<tb_GiaBan>(new Action<tb_GiaBan>(this.attach_tb_GiaBans), new Action<tb_GiaBan>(this.detach_tb_GiaBans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBangGia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBangGia
		{
			get
			{
				return this._MaBangGia;
			}
			set
			{
				if ((this._MaBangGia != value))
				{
					this.OnMaBangGiaChanging(value);
					this.SendPropertyChanging();
					this._MaBangGia = value;
					this.SendPropertyChanged("MaBangGia");
					this.OnMaBangGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBangGia", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string TenBangGia
		{
			get
			{
				return this._TenBangGia;
			}
			set
			{
				if ((this._TenBangGia != value))
				{
					this.OnTenBangGiaChanging(value);
					this.SendPropertyChanging();
					this._TenBangGia = value;
					this.SendPropertyChanged("TenBangGia");
					this.OnTenBangGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_BangGia_tb_ChiTietHDBan", Storage="_tb_ChiTietHDBans", ThisKey="MaBangGia", OtherKey="MaBangGia")]
		public EntitySet<tb_ChiTietHDBan> tb_ChiTietHDBans
		{
			get
			{
				return this._tb_ChiTietHDBans;
			}
			set
			{
				this._tb_ChiTietHDBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_BangGia_tb_GiaBan", Storage="_tb_GiaBans", ThisKey="MaBangGia", OtherKey="MaBangGia")]
		public EntitySet<tb_GiaBan> tb_GiaBans
		{
			get
			{
				return this._tb_GiaBans;
			}
			set
			{
				this._tb_GiaBans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_ChiTietHDBans(tb_ChiTietHDBan entity)
		{
			this.SendPropertyChanging();
			entity.tb_BangGia = this;
		}
		
		private void detach_tb_ChiTietHDBans(tb_ChiTietHDBan entity)
		{
			this.SendPropertyChanging();
			entity.tb_BangGia = null;
		}
		
		private void attach_tb_GiaBans(tb_GiaBan entity)
		{
			this.SendPropertyChanging();
			entity.tb_BangGia = this;
		}
		
		private void detach_tb_GiaBans(tb_GiaBan entity)
		{
			this.SendPropertyChanging();
			entity.tb_BangGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_ThuongHieu")]
	public partial class tb_ThuongHieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaThuongHieu;
		
		private string _TenThuongHieu;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_SanPham> _tb_SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThuongHieuChanging(int value);
    partial void OnMaThuongHieuChanged();
    partial void OnTenThuongHieuChanging(string value);
    partial void OnTenThuongHieuChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_ThuongHieu()
		{
			this._tb_SanPhams = new EntitySet<tb_SanPham>(new Action<tb_SanPham>(this.attach_tb_SanPhams), new Action<tb_SanPham>(this.detach_tb_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuongHieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaThuongHieu
		{
			get
			{
				return this._MaThuongHieu;
			}
			set
			{
				if ((this._MaThuongHieu != value))
				{
					this.OnMaThuongHieuChanging(value);
					this.SendPropertyChanging();
					this._MaThuongHieu = value;
					this.SendPropertyChanged("MaThuongHieu");
					this.OnMaThuongHieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThuongHieu", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string TenThuongHieu
		{
			get
			{
				return this._TenThuongHieu;
			}
			set
			{
				if ((this._TenThuongHieu != value))
				{
					this.OnTenThuongHieuChanging(value);
					this.SendPropertyChanging();
					this._TenThuongHieu = value;
					this.SendPropertyChanged("TenThuongHieu");
					this.OnTenThuongHieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_ThuongHieu_tb_SanPham", Storage="_tb_SanPhams", ThisKey="MaThuongHieu", OtherKey="MaThuongHieu")]
		public EntitySet<tb_SanPham> tb_SanPhams
		{
			get
			{
				return this._tb_SanPhams;
			}
			set
			{
				this._tb_SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_SanPhams(tb_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.tb_ThuongHieu = this;
		}
		
		private void detach_tb_SanPhams(tb_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.tb_ThuongHieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_ChiTietHDBan")]
	public partial class tb_ChiTietHDBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHDBan;
		
		private string _MaSanPham;
		
		private int _MaBangGia;
		
		private int _SoLuong;
		
		private System.Nullable<decimal> _DonGia;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private EntityRef<tb_BangGia> _tb_BangGia;
		
		private EntityRef<tb_SanPham> _tb_SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDBanChanging(string value);
    partial void OnMaHDBanChanged();
    partial void OnMaSanPhamChanging(string value);
    partial void OnMaSanPhamChanged();
    partial void OnMaBangGiaChanging(int value);
    partial void OnMaBangGiaChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public tb_ChiTietHDBan()
		{
			this._tb_BangGia = default(EntityRef<tb_BangGia>);
			this._tb_SanPham = default(EntityRef<tb_SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDBan", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHDBan
		{
			get
			{
				return this._MaHDBan;
			}
			set
			{
				if ((this._MaHDBan != value))
				{
					this.OnMaHDBanChanging(value);
					this.SendPropertyChanging();
					this._MaHDBan = value;
					this.SendPropertyChanged("MaHDBan");
					this.OnMaHDBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					if (this._tb_SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBangGia", DbType="Int NOT NULL")]
		public int MaBangGia
		{
			get
			{
				return this._MaBangGia;
			}
			set
			{
				if ((this._MaBangGia != value))
				{
					if (this._tb_BangGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBangGiaChanging(value);
					this.SendPropertyChanging();
					this._MaBangGia = value;
					this.SendPropertyChanged("MaBangGia");
					this.OnMaBangGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_BangGia_tb_ChiTietHDBan", Storage="_tb_BangGia", ThisKey="MaBangGia", OtherKey="MaBangGia", IsForeignKey=true)]
		public tb_BangGia tb_BangGia
		{
			get
			{
				return this._tb_BangGia.Entity;
			}
			set
			{
				tb_BangGia previousValue = this._tb_BangGia.Entity;
				if (((previousValue != value) 
							|| (this._tb_BangGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_BangGia.Entity = null;
						previousValue.tb_ChiTietHDBans.Remove(this);
					}
					this._tb_BangGia.Entity = value;
					if ((value != null))
					{
						value.tb_ChiTietHDBans.Add(this);
						this._MaBangGia = value.MaBangGia;
					}
					else
					{
						this._MaBangGia = default(int);
					}
					this.SendPropertyChanged("tb_BangGia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_SanPham_tb_ChiTietHDBan", Storage="_tb_SanPham", ThisKey="MaSanPham", OtherKey="MaSanPham", IsForeignKey=true)]
		public tb_SanPham tb_SanPham
		{
			get
			{
				return this._tb_SanPham.Entity;
			}
			set
			{
				tb_SanPham previousValue = this._tb_SanPham.Entity;
				if (((previousValue != value) 
							|| (this._tb_SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_SanPham.Entity = null;
						previousValue.tb_ChiTietHDBans.Remove(this);
					}
					this._tb_SanPham.Entity = value;
					if ((value != null))
					{
						value.tb_ChiTietHDBans.Add(this);
						this._MaSanPham = value.MaSanPham;
					}
					else
					{
						this._MaSanPham = default(string);
					}
					this.SendPropertyChanged("tb_SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_ChiTietHDNhap")]
	public partial class tb_ChiTietHDNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHDNhap;
		
		private string _MaSanPham;
		
		private int _SoLuong;
		
		private System.Nullable<decimal> _GiaNhap;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private EntityRef<tb_HoaDonNhap> _tb_HoaDonNhap;
		
		private EntityRef<tb_SanPham> _tb_SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDNhapChanging(string value);
    partial void OnMaHDNhapChanged();
    partial void OnMaSanPhamChanging(string value);
    partial void OnMaSanPhamChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnGiaNhapChanging(System.Nullable<decimal> value);
    partial void OnGiaNhapChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public tb_ChiTietHDNhap()
		{
			this._tb_HoaDonNhap = default(EntityRef<tb_HoaDonNhap>);
			this._tb_SanPham = default(EntityRef<tb_SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDNhap", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHDNhap
		{
			get
			{
				return this._MaHDNhap;
			}
			set
			{
				if ((this._MaHDNhap != value))
				{
					if (this._tb_HoaDonNhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDNhapChanging(value);
					this.SendPropertyChanging();
					this._MaHDNhap = value;
					this.SendPropertyChanged("MaHDNhap");
					this.OnMaHDNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					if (this._tb_SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaNhap", DbType="Money")]
		public System.Nullable<decimal> GiaNhap
		{
			get
			{
				return this._GiaNhap;
			}
			set
			{
				if ((this._GiaNhap != value))
				{
					this.OnGiaNhapChanging(value);
					this.SendPropertyChanging();
					this._GiaNhap = value;
					this.SendPropertyChanged("GiaNhap");
					this.OnGiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_HoaDonNhap_tb_ChiTietHDNhap", Storage="_tb_HoaDonNhap", ThisKey="MaHDNhap", OtherKey="MaHDNhap", IsForeignKey=true)]
		public tb_HoaDonNhap tb_HoaDonNhap
		{
			get
			{
				return this._tb_HoaDonNhap.Entity;
			}
			set
			{
				tb_HoaDonNhap previousValue = this._tb_HoaDonNhap.Entity;
				if (((previousValue != value) 
							|| (this._tb_HoaDonNhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_HoaDonNhap.Entity = null;
						previousValue.tb_ChiTietHDNhaps.Remove(this);
					}
					this._tb_HoaDonNhap.Entity = value;
					if ((value != null))
					{
						value.tb_ChiTietHDNhaps.Add(this);
						this._MaHDNhap = value.MaHDNhap;
					}
					else
					{
						this._MaHDNhap = default(string);
					}
					this.SendPropertyChanged("tb_HoaDonNhap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_SanPham_tb_ChiTietHDNhap", Storage="_tb_SanPham", ThisKey="MaSanPham", OtherKey="MaSanPham", IsForeignKey=true)]
		public tb_SanPham tb_SanPham
		{
			get
			{
				return this._tb_SanPham.Entity;
			}
			set
			{
				tb_SanPham previousValue = this._tb_SanPham.Entity;
				if (((previousValue != value) 
							|| (this._tb_SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_SanPham.Entity = null;
						previousValue.tb_ChiTietHDNhaps.Remove(this);
					}
					this._tb_SanPham.Entity = value;
					if ((value != null))
					{
						value.tb_ChiTietHDNhaps.Add(this);
						this._MaSanPham = value.MaSanPham;
					}
					else
					{
						this._MaSanPham = default(string);
					}
					this.SendPropertyChanged("tb_SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_GiaBan")]
	public partial class tb_GiaBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBangGia;
		
		private string _MaSanPham;
		
		private decimal _GiaBan;
		
		private EntityRef<tb_BangGia> _tb_BangGia;
		
		private EntityRef<tb_SanPham> _tb_SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBangGiaChanging(int value);
    partial void OnMaBangGiaChanged();
    partial void OnMaSanPhamChanging(string value);
    partial void OnMaSanPhamChanged();
    partial void OnGiaBanChanging(decimal value);
    partial void OnGiaBanChanged();
    #endregion
		
		public tb_GiaBan()
		{
			this._tb_BangGia = default(EntityRef<tb_BangGia>);
			this._tb_SanPham = default(EntityRef<tb_SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBangGia", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaBangGia
		{
			get
			{
				return this._MaBangGia;
			}
			set
			{
				if ((this._MaBangGia != value))
				{
					if (this._tb_BangGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBangGiaChanging(value);
					this.SendPropertyChanging();
					this._MaBangGia = value;
					this.SendPropertyChanged("MaBangGia");
					this.OnMaBangGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					if (this._tb_SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Money NOT NULL")]
		public decimal GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this.OnGiaBanChanging(value);
					this.SendPropertyChanging();
					this._GiaBan = value;
					this.SendPropertyChanged("GiaBan");
					this.OnGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_BangGia_tb_GiaBan", Storage="_tb_BangGia", ThisKey="MaBangGia", OtherKey="MaBangGia", IsForeignKey=true)]
		public tb_BangGia tb_BangGia
		{
			get
			{
				return this._tb_BangGia.Entity;
			}
			set
			{
				tb_BangGia previousValue = this._tb_BangGia.Entity;
				if (((previousValue != value) 
							|| (this._tb_BangGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_BangGia.Entity = null;
						previousValue.tb_GiaBans.Remove(this);
					}
					this._tb_BangGia.Entity = value;
					if ((value != null))
					{
						value.tb_GiaBans.Add(this);
						this._MaBangGia = value.MaBangGia;
					}
					else
					{
						this._MaBangGia = default(int);
					}
					this.SendPropertyChanged("tb_BangGia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_SanPham_tb_GiaBan", Storage="_tb_SanPham", ThisKey="MaSanPham", OtherKey="MaSanPham", IsForeignKey=true)]
		public tb_SanPham tb_SanPham
		{
			get
			{
				return this._tb_SanPham.Entity;
			}
			set
			{
				tb_SanPham previousValue = this._tb_SanPham.Entity;
				if (((previousValue != value) 
							|| (this._tb_SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_SanPham.Entity = null;
						previousValue.tb_GiaBans.Remove(this);
					}
					this._tb_SanPham.Entity = value;
					if ((value != null))
					{
						value.tb_GiaBans.Add(this);
						this._MaSanPham = value.MaSanPham;
					}
					else
					{
						this._MaSanPham = default(string);
					}
					this.SendPropertyChanged("tb_SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_HoaDonBan")]
	public partial class tb_HoaDonBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHDBan;
		
		private string _MaNV;
		
		private string _MaKH;
		
		private System.DateTime _NgayLap;
		
		private System.Nullable<decimal> _TongTien;
		
		private System.Nullable<decimal> _GiamGia;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private System.Nullable<bool> _TrangThai;
		
		private EntityRef<tb_KhachHang> _tb_KhachHang;
		
		private EntityRef<tb_NhanVien> _tb_NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDBanChanging(string value);
    partial void OnMaHDBanChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnNgayLapChanging(System.DateTime value);
    partial void OnNgayLapChanged();
    partial void OnTongTienChanging(System.Nullable<decimal> value);
    partial void OnTongTienChanged();
    partial void OnGiamGiaChanging(System.Nullable<decimal> value);
    partial void OnGiamGiaChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public tb_HoaDonBan()
		{
			this._tb_KhachHang = default(EntityRef<tb_KhachHang>);
			this._tb_NhanVien = default(EntityRef<tb_NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDBan", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHDBan
		{
			get
			{
				return this._MaHDBan;
			}
			set
			{
				if ((this._MaHDBan != value))
				{
					this.OnMaHDBanChanging(value);
					this.SendPropertyChanging();
					this._MaHDBan = value;
					this.SendPropertyChanged("MaHDBan");
					this.OnMaHDBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._tb_NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(7)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._tb_KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="DateTime NOT NULL")]
		public System.DateTime NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Money")]
		public System.Nullable<decimal> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Money")]
		public System.Nullable<decimal> GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_KhachHang_tb_HoaDonBan", Storage="_tb_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public tb_KhachHang tb_KhachHang
		{
			get
			{
				return this._tb_KhachHang.Entity;
			}
			set
			{
				tb_KhachHang previousValue = this._tb_KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._tb_KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_KhachHang.Entity = null;
						previousValue.tb_HoaDonBans.Remove(this);
					}
					this._tb_KhachHang.Entity = value;
					if ((value != null))
					{
						value.tb_HoaDonBans.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("tb_KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NhanVien_tb_HoaDonBan", Storage="_tb_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public tb_NhanVien tb_NhanVien
		{
			get
			{
				return this._tb_NhanVien.Entity;
			}
			set
			{
				tb_NhanVien previousValue = this._tb_NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tb_NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_NhanVien.Entity = null;
						previousValue.tb_HoaDonBans.Remove(this);
					}
					this._tb_NhanVien.Entity = value;
					if ((value != null))
					{
						value.tb_HoaDonBans.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("tb_NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_HoaDonNhap")]
	public partial class tb_HoaDonNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHDNhap;
		
		private string _MaNV;
		
		private System.DateTime _NgayLap;
		
		private EntitySet<tb_ChiTietHDNhap> _tb_ChiTietHDNhaps;
		
		private EntityRef<tb_NhanVien> _tb_NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDNhapChanging(string value);
    partial void OnMaHDNhapChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnNgayLapChanging(System.DateTime value);
    partial void OnNgayLapChanged();
    #endregion
		
		public tb_HoaDonNhap()
		{
			this._tb_ChiTietHDNhaps = new EntitySet<tb_ChiTietHDNhap>(new Action<tb_ChiTietHDNhap>(this.attach_tb_ChiTietHDNhaps), new Action<tb_ChiTietHDNhap>(this.detach_tb_ChiTietHDNhaps));
			this._tb_NhanVien = default(EntityRef<tb_NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDNhap", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHDNhap
		{
			get
			{
				return this._MaHDNhap;
			}
			set
			{
				if ((this._MaHDNhap != value))
				{
					this.OnMaHDNhapChanging(value);
					this.SendPropertyChanging();
					this._MaHDNhap = value;
					this.SendPropertyChanged("MaHDNhap");
					this.OnMaHDNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(7)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._tb_NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="DateTime NOT NULL")]
		public System.DateTime NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_HoaDonNhap_tb_ChiTietHDNhap", Storage="_tb_ChiTietHDNhaps", ThisKey="MaHDNhap", OtherKey="MaHDNhap")]
		public EntitySet<tb_ChiTietHDNhap> tb_ChiTietHDNhaps
		{
			get
			{
				return this._tb_ChiTietHDNhaps;
			}
			set
			{
				this._tb_ChiTietHDNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NhanVien_tb_HoaDonNhap", Storage="_tb_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public tb_NhanVien tb_NhanVien
		{
			get
			{
				return this._tb_NhanVien.Entity;
			}
			set
			{
				tb_NhanVien previousValue = this._tb_NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tb_NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_NhanVien.Entity = null;
						previousValue.tb_HoaDonNhaps.Remove(this);
					}
					this._tb_NhanVien.Entity = value;
					if ((value != null))
					{
						value.tb_HoaDonNhaps.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("tb_NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_ChiTietHDNhaps(tb_ChiTietHDNhap entity)
		{
			this.SendPropertyChanging();
			entity.tb_HoaDonNhap = this;
		}
		
		private void detach_tb_ChiTietHDNhaps(tb_ChiTietHDNhap entity)
		{
			this.SendPropertyChanging();
			entity.tb_HoaDonNhap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Identity")]
	public partial class tb_Identity
	{
		
		private System.Nullable<int> _NhanVien;
		
		private System.Nullable<int> _SanPham;
		
		private System.Nullable<int> _HoaDonBan;
		
		private System.Nullable<int> _HoaDonNhap;
		
		public tb_Identity()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVien", DbType="Int")]
		public System.Nullable<int> NhanVien
		{
			get
			{
				return this._NhanVien;
			}
			set
			{
				if ((this._NhanVien != value))
				{
					this._NhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanPham", DbType="Int")]
		public System.Nullable<int> SanPham
		{
			get
			{
				return this._SanPham;
			}
			set
			{
				if ((this._SanPham != value))
				{
					this._SanPham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoaDonBan", DbType="Int")]
		public System.Nullable<int> HoaDonBan
		{
			get
			{
				return this._HoaDonBan;
			}
			set
			{
				if ((this._HoaDonBan != value))
				{
					this._HoaDonBan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoaDonNhap", DbType="Int")]
		public System.Nullable<int> HoaDonNhap
		{
			get
			{
				return this._HoaDonNhap;
			}
			set
			{
				if ((this._HoaDonNhap != value))
				{
					this._HoaDonNhap = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_KhachHang")]
	public partial class tb_KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private string _DienThoai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_HoaDonBan> _tb_HoaDonBans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_KhachHang()
		{
			this._tb_HoaDonBans = new EntitySet<tb_HoaDonBan>(new Action<tb_HoaDonBan>(this.attach_tb_HoaDonBans), new Action<tb_HoaDonBan>(this.detach_tb_HoaDonBans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(120)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_KhachHang_tb_HoaDonBan", Storage="_tb_HoaDonBans", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<tb_HoaDonBan> tb_HoaDonBans
		{
			get
			{
				return this._tb_HoaDonBans;
			}
			set
			{
				this._tb_HoaDonBans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_HoaDonBans(tb_HoaDonBan entity)
		{
			this.SendPropertyChanging();
			entity.tb_KhachHang = this;
		}
		
		private void detach_tb_HoaDonBans(tb_HoaDonBan entity)
		{
			this.SendPropertyChanging();
			entity.tb_KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_NhanVien")]
	public partial class tb_NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private string _DienThoai;
		
		private System.DateTime _NgaySinh;
		
		private string _Username;
		
		private string _DiaChi;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_HoaDonBan> _tb_HoaDonBans;
		
		private EntitySet<tb_HoaDonNhap> _tb_HoaDonNhaps;
		
		private EntityRef<tb_TaiKhoan> _tb_TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_NhanVien()
		{
			this._tb_HoaDonBans = new EntitySet<tb_HoaDonBan>(new Action<tb_HoaDonBan>(this.attach_tb_HoaDonBans), new Action<tb_HoaDonBan>(this.detach_tb_HoaDonBans));
			this._tb_HoaDonNhaps = new EntitySet<tb_HoaDonNhap>(new Action<tb_HoaDonNhap>(this.attach_tb_HoaDonNhaps), new Action<tb_HoaDonNhap>(this.detach_tb_HoaDonNhaps));
			this._tb_TaiKhoan = default(EntityRef<tb_TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					if (this._tb_TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(120)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NhanVien_tb_HoaDonBan", Storage="_tb_HoaDonBans", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<tb_HoaDonBan> tb_HoaDonBans
		{
			get
			{
				return this._tb_HoaDonBans;
			}
			set
			{
				this._tb_HoaDonBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NhanVien_tb_HoaDonNhap", Storage="_tb_HoaDonNhaps", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<tb_HoaDonNhap> tb_HoaDonNhaps
		{
			get
			{
				return this._tb_HoaDonNhaps;
			}
			set
			{
				this._tb_HoaDonNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_TaiKhoan_tb_NhanVien", Storage="_tb_TaiKhoan", ThisKey="Username", OtherKey="Username", IsForeignKey=true)]
		public tb_TaiKhoan tb_TaiKhoan
		{
			get
			{
				return this._tb_TaiKhoan.Entity;
			}
			set
			{
				tb_TaiKhoan previousValue = this._tb_TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._tb_TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_TaiKhoan.Entity = null;
						previousValue.tb_NhanViens.Remove(this);
					}
					this._tb_TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.tb_NhanViens.Add(this);
						this._Username = value.Username;
					}
					else
					{
						this._Username = default(string);
					}
					this.SendPropertyChanged("tb_TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_HoaDonBans(tb_HoaDonBan entity)
		{
			this.SendPropertyChanging();
			entity.tb_NhanVien = this;
		}
		
		private void detach_tb_HoaDonBans(tb_HoaDonBan entity)
		{
			this.SendPropertyChanging();
			entity.tb_NhanVien = null;
		}
		
		private void attach_tb_HoaDonNhaps(tb_HoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.tb_NhanVien = this;
		}
		
		private void detach_tb_HoaDonNhaps(tb_HoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.tb_NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_NhomSanPham")]
	public partial class tb_NhomSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNSP;
		
		private string _TenNSP;
		
		private System.Nullable<int> _NSPCha;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_NhomSanPham> _tb_NhomSanPhams;
		
		private EntitySet<tb_SanPham> _tb_SanPhams;
		
		private EntityRef<tb_NhomSanPham> _tb_NhomSanPham1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNSPChanging(int value);
    partial void OnMaNSPChanged();
    partial void OnTenNSPChanging(string value);
    partial void OnTenNSPChanged();
    partial void OnNSPChaChanging(System.Nullable<int> value);
    partial void OnNSPChaChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_NhomSanPham()
		{
			this._tb_NhomSanPhams = new EntitySet<tb_NhomSanPham>(new Action<tb_NhomSanPham>(this.attach_tb_NhomSanPhams), new Action<tb_NhomSanPham>(this.detach_tb_NhomSanPhams));
			this._tb_SanPhams = new EntitySet<tb_SanPham>(new Action<tb_SanPham>(this.attach_tb_SanPhams), new Action<tb_SanPham>(this.detach_tb_SanPhams));
			this._tb_NhomSanPham1 = default(EntityRef<tb_NhomSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNSP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNSP
		{
			get
			{
				return this._MaNSP;
			}
			set
			{
				if ((this._MaNSP != value))
				{
					this.OnMaNSPChanging(value);
					this.SendPropertyChanging();
					this._MaNSP = value;
					this.SendPropertyChanged("MaNSP");
					this.OnMaNSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNSP", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string TenNSP
		{
			get
			{
				return this._TenNSP;
			}
			set
			{
				if ((this._TenNSP != value))
				{
					this.OnTenNSPChanging(value);
					this.SendPropertyChanging();
					this._TenNSP = value;
					this.SendPropertyChanged("TenNSP");
					this.OnTenNSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSPCha", DbType="Int")]
		public System.Nullable<int> NSPCha
		{
			get
			{
				return this._NSPCha;
			}
			set
			{
				if ((this._NSPCha != value))
				{
					if (this._tb_NhomSanPham1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNSPChaChanging(value);
					this.SendPropertyChanging();
					this._NSPCha = value;
					this.SendPropertyChanged("NSPCha");
					this.OnNSPChaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NhomSanPham_tb_NhomSanPham", Storage="_tb_NhomSanPhams", ThisKey="MaNSP", OtherKey="NSPCha")]
		public EntitySet<tb_NhomSanPham> tb_NhomSanPhams
		{
			get
			{
				return this._tb_NhomSanPhams;
			}
			set
			{
				this._tb_NhomSanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NhomSanPham_tb_SanPham", Storage="_tb_SanPhams", ThisKey="MaNSP", OtherKey="MaNSP")]
		public EntitySet<tb_SanPham> tb_SanPhams
		{
			get
			{
				return this._tb_SanPhams;
			}
			set
			{
				this._tb_SanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NhomSanPham_tb_NhomSanPham", Storage="_tb_NhomSanPham1", ThisKey="NSPCha", OtherKey="MaNSP", IsForeignKey=true)]
		public tb_NhomSanPham tb_NhomSanPham1
		{
			get
			{
				return this._tb_NhomSanPham1.Entity;
			}
			set
			{
				tb_NhomSanPham previousValue = this._tb_NhomSanPham1.Entity;
				if (((previousValue != value) 
							|| (this._tb_NhomSanPham1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_NhomSanPham1.Entity = null;
						previousValue.tb_NhomSanPhams.Remove(this);
					}
					this._tb_NhomSanPham1.Entity = value;
					if ((value != null))
					{
						value.tb_NhomSanPhams.Add(this);
						this._NSPCha = value.MaNSP;
					}
					else
					{
						this._NSPCha = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_NhomSanPham1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_NhomSanPhams(tb_NhomSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tb_NhomSanPham1 = this;
		}
		
		private void detach_tb_NhomSanPhams(tb_NhomSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tb_NhomSanPham1 = null;
		}
		
		private void attach_tb_SanPhams(tb_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.tb_NhomSanPham = this;
		}
		
		private void detach_tb_SanPhams(tb_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.tb_NhomSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_SanPham")]
	public partial class tb_SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSanPham;
		
		private string _MaVach;
		
		private string _TenSP;
		
		private int _MaNSP;
		
		private System.Nullable<int> _MaThuongHieu;
		
		private System.Nullable<decimal> _GiaVon;
		
		private System.Nullable<int> _TonKho;
		
		private System.Nullable<int> _DaMua;
		
		private string _UrlHinh;
		
		private string _MoTa;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_ChiTietHDBan> _tb_ChiTietHDBans;
		
		private EntitySet<tb_ChiTietHDNhap> _tb_ChiTietHDNhaps;
		
		private EntitySet<tb_GiaBan> _tb_GiaBans;
		
		private EntityRef<tb_NhomSanPham> _tb_NhomSanPham;
		
		private EntityRef<tb_ThuongHieu> _tb_ThuongHieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSanPhamChanging(string value);
    partial void OnMaSanPhamChanged();
    partial void OnMaVachChanging(string value);
    partial void OnMaVachChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnMaNSPChanging(int value);
    partial void OnMaNSPChanged();
    partial void OnMaThuongHieuChanging(System.Nullable<int> value);
    partial void OnMaThuongHieuChanged();
    partial void OnGiaVonChanging(System.Nullable<decimal> value);
    partial void OnGiaVonChanged();
    partial void OnTonKhoChanging(System.Nullable<int> value);
    partial void OnTonKhoChanged();
    partial void OnDaMuaChanging(System.Nullable<int> value);
    partial void OnDaMuaChanged();
    partial void OnUrlHinhChanging(string value);
    partial void OnUrlHinhChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_SanPham()
		{
			this._tb_ChiTietHDBans = new EntitySet<tb_ChiTietHDBan>(new Action<tb_ChiTietHDBan>(this.attach_tb_ChiTietHDBans), new Action<tb_ChiTietHDBan>(this.detach_tb_ChiTietHDBans));
			this._tb_ChiTietHDNhaps = new EntitySet<tb_ChiTietHDNhap>(new Action<tb_ChiTietHDNhap>(this.attach_tb_ChiTietHDNhaps), new Action<tb_ChiTietHDNhap>(this.detach_tb_ChiTietHDNhaps));
			this._tb_GiaBans = new EntitySet<tb_GiaBan>(new Action<tb_GiaBan>(this.attach_tb_GiaBans), new Action<tb_GiaBan>(this.detach_tb_GiaBans));
			this._tb_NhomSanPham = default(EntityRef<tb_NhomSanPham>);
			this._tb_ThuongHieu = default(EntityRef<tb_ThuongHieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVach", DbType="VarChar(20)")]
		public string MaVach
		{
			get
			{
				return this._MaVach;
			}
			set
			{
				if ((this._MaVach != value))
				{
					this.OnMaVachChanging(value);
					this.SendPropertyChanging();
					this._MaVach = value;
					this.SendPropertyChanged("MaVach");
					this.OnMaVachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNSP", DbType="Int NOT NULL")]
		public int MaNSP
		{
			get
			{
				return this._MaNSP;
			}
			set
			{
				if ((this._MaNSP != value))
				{
					if (this._tb_NhomSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNSPChanging(value);
					this.SendPropertyChanging();
					this._MaNSP = value;
					this.SendPropertyChanged("MaNSP");
					this.OnMaNSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuongHieu", DbType="Int")]
		public System.Nullable<int> MaThuongHieu
		{
			get
			{
				return this._MaThuongHieu;
			}
			set
			{
				if ((this._MaThuongHieu != value))
				{
					if (this._tb_ThuongHieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThuongHieuChanging(value);
					this.SendPropertyChanging();
					this._MaThuongHieu = value;
					this.SendPropertyChanged("MaThuongHieu");
					this.OnMaThuongHieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaVon", DbType="Money")]
		public System.Nullable<decimal> GiaVon
		{
			get
			{
				return this._GiaVon;
			}
			set
			{
				if ((this._GiaVon != value))
				{
					this.OnGiaVonChanging(value);
					this.SendPropertyChanging();
					this._GiaVon = value;
					this.SendPropertyChanged("GiaVon");
					this.OnGiaVonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonKho", DbType="Int")]
		public System.Nullable<int> TonKho
		{
			get
			{
				return this._TonKho;
			}
			set
			{
				if ((this._TonKho != value))
				{
					this.OnTonKhoChanging(value);
					this.SendPropertyChanging();
					this._TonKho = value;
					this.SendPropertyChanged("TonKho");
					this.OnTonKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaMua", DbType="Int")]
		public System.Nullable<int> DaMua
		{
			get
			{
				return this._DaMua;
			}
			set
			{
				if ((this._DaMua != value))
				{
					this.OnDaMuaChanging(value);
					this.SendPropertyChanging();
					this._DaMua = value;
					this.SendPropertyChanged("DaMua");
					this.OnDaMuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlHinh", DbType="VarChar(1000)")]
		public string UrlHinh
		{
			get
			{
				return this._UrlHinh;
			}
			set
			{
				if ((this._UrlHinh != value))
				{
					this.OnUrlHinhChanging(value);
					this.SendPropertyChanging();
					this._UrlHinh = value;
					this.SendPropertyChanged("UrlHinh");
					this.OnUrlHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_SanPham_tb_ChiTietHDBan", Storage="_tb_ChiTietHDBans", ThisKey="MaSanPham", OtherKey="MaSanPham")]
		public EntitySet<tb_ChiTietHDBan> tb_ChiTietHDBans
		{
			get
			{
				return this._tb_ChiTietHDBans;
			}
			set
			{
				this._tb_ChiTietHDBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_SanPham_tb_ChiTietHDNhap", Storage="_tb_ChiTietHDNhaps", ThisKey="MaSanPham", OtherKey="MaSanPham")]
		public EntitySet<tb_ChiTietHDNhap> tb_ChiTietHDNhaps
		{
			get
			{
				return this._tb_ChiTietHDNhaps;
			}
			set
			{
				this._tb_ChiTietHDNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_SanPham_tb_GiaBan", Storage="_tb_GiaBans", ThisKey="MaSanPham", OtherKey="MaSanPham")]
		public EntitySet<tb_GiaBan> tb_GiaBans
		{
			get
			{
				return this._tb_GiaBans;
			}
			set
			{
				this._tb_GiaBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NhomSanPham_tb_SanPham", Storage="_tb_NhomSanPham", ThisKey="MaNSP", OtherKey="MaNSP", IsForeignKey=true)]
		public tb_NhomSanPham tb_NhomSanPham
		{
			get
			{
				return this._tb_NhomSanPham.Entity;
			}
			set
			{
				tb_NhomSanPham previousValue = this._tb_NhomSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tb_NhomSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_NhomSanPham.Entity = null;
						previousValue.tb_SanPhams.Remove(this);
					}
					this._tb_NhomSanPham.Entity = value;
					if ((value != null))
					{
						value.tb_SanPhams.Add(this);
						this._MaNSP = value.MaNSP;
					}
					else
					{
						this._MaNSP = default(int);
					}
					this.SendPropertyChanged("tb_NhomSanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_ThuongHieu_tb_SanPham", Storage="_tb_ThuongHieu", ThisKey="MaThuongHieu", OtherKey="MaThuongHieu", IsForeignKey=true)]
		public tb_ThuongHieu tb_ThuongHieu
		{
			get
			{
				return this._tb_ThuongHieu.Entity;
			}
			set
			{
				tb_ThuongHieu previousValue = this._tb_ThuongHieu.Entity;
				if (((previousValue != value) 
							|| (this._tb_ThuongHieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_ThuongHieu.Entity = null;
						previousValue.tb_SanPhams.Remove(this);
					}
					this._tb_ThuongHieu.Entity = value;
					if ((value != null))
					{
						value.tb_SanPhams.Add(this);
						this._MaThuongHieu = value.MaThuongHieu;
					}
					else
					{
						this._MaThuongHieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_ThuongHieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_ChiTietHDBans(tb_ChiTietHDBan entity)
		{
			this.SendPropertyChanging();
			entity.tb_SanPham = this;
		}
		
		private void detach_tb_ChiTietHDBans(tb_ChiTietHDBan entity)
		{
			this.SendPropertyChanging();
			entity.tb_SanPham = null;
		}
		
		private void attach_tb_ChiTietHDNhaps(tb_ChiTietHDNhap entity)
		{
			this.SendPropertyChanging();
			entity.tb_SanPham = this;
		}
		
		private void detach_tb_ChiTietHDNhaps(tb_ChiTietHDNhap entity)
		{
			this.SendPropertyChanging();
			entity.tb_SanPham = null;
		}
		
		private void attach_tb_GiaBans(tb_GiaBan entity)
		{
			this.SendPropertyChanging();
			entity.tb_SanPham = this;
		}
		
		private void detach_tb_GiaBans(tb_GiaBan entity)
		{
			this.SendPropertyChanging();
			entity.tb_SanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_TaiKhoan")]
	public partial class tb_TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Password;
		
		private System.Nullable<bool> _IsAdmin;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_NhanVien> _tb_NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnIsAdminChanging(System.Nullable<bool> value);
    partial void OnIsAdminChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_TaiKhoan()
		{
			this._tb_NhanViens = new EntitySet<tb_NhanVien>(new Action<tb_NhanVien>(this.attach_tb_NhanViens), new Action<tb_NhanVien>(this.detach_tb_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit")]
		public System.Nullable<bool> IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this.OnIsAdminChanging(value);
					this.SendPropertyChanging();
					this._IsAdmin = value;
					this.SendPropertyChanged("IsAdmin");
					this.OnIsAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_TaiKhoan_tb_NhanVien", Storage="_tb_NhanViens", ThisKey="Username", OtherKey="Username")]
		public EntitySet<tb_NhanVien> tb_NhanViens
		{
			get
			{
				return this._tb_NhanViens;
			}
			set
			{
				this._tb_NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_NhanViens(tb_NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tb_TaiKhoan = this;
		}
		
		private void detach_tb_NhanViens(tb_NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tb_TaiKhoan = null;
		}
	}
}
#pragma warning restore 1591
